### ISSUE TITLE
Error rate and runtime

### ISSUE THREAD

**Issue by supermaxiste** [FelixKrueger/Sherman#6]
Hi,

I'm using Sherman to simulate some BS reads with the following parameters:  

        - 80 million reads   
        - 80% conversion rate (20% methylation)   
        - 125bp length for all reads  
        - Paired end reads  
        - Constant Phred quality score of 40  
        - Error rate of 0.01%  

The first time I tried to simulate I let Sherman run for a couple of days before giving up and stopping it. I tried again this week and now it's been running for 71h and it's still stuck on the same process, which is the error curve:

`Genome folder was specified as /path/to/genome/`

`Selected general parameters:`
`----------------------------------------------------------------------------------------------------`
`Paired-end reads selected. Fragment length will be 70-400 bp`
`sequence length:        125 bp`
`number of sequences being generated:    80000000`

`Possible sources of contamination:`
`----------------------------------------------------------------------------------------------------`
`overall error rate:     0.01%`
`bisulfite conversion rate:      80%`

`Generating quality values with a user defined decaying per-bp error rate of 0.01%`
`Starting to work out the slope of the error curve`

By setting the error rate to zero, the simulation runs quite smoothly, so the culprit is clearly the error rate. My question is: is this normal?

Thank you in advance for your answer!

Stefan

**Comment by FelixKrueger** [comment]
Hi Stefan,

Apologies for making you sit in front of your screen for several days in a row - this is certainly not intended (or nomal). I would say the process of working out the decaying error model should not take longer than one second, anything above that is most likely getting itself stuck in something that won't ever finish. I just confirmed this over here, the following command:
```
Sherman -e 0.01 -l 125 --genome /bi/scratch/Genomes/Mouse/GRCm38/ --paired --CR 80
```
which should be pretty much what you were using, gets stuck on working out the slope of the error curve, while:

```
Sherman -e 0.1 -l 125 --genome /bi/scratch/Genomes/Mouse/GRCm38/ --paired --CR 80
```
comes up with this model instantly:
```
Error rates per bp will be modelled according to the formula:
default base quality - 0.034286*position[bp] + 0.0009263*(position[bp]**2)) - 0.00001*(position[bp]**3)*1.5364)
```

The background for this model is, that in ~2011, when we tried to come up with a error decay formula by fitting a curve in SPSS to typical Illumina data, the simulated read lengths were mainly around 40-75bp. It seems that increasing the read length too much, while selecting very low or very high error rates doesn't seem seem to be compatible with the formula.

I just ran a few test commands, and it turns out that the command you tried works fine up to a read length of 124 bp, but gets stuck above that. So you were indeed *very* unlucky there. 

I will add a comment to that option so that people don't wait for more than a second for it to work out the slope of the curve. 

To save some time now, I would probably recommend that you don't simulated 80M reads but maybe start with a smaller fraction and multiply the time/stats accordingly? Unless you need that many reads of course...

Cheers, Felix

**Comment by FelixKrueger** [comment]
Addressed here: 4c78712d5609be917487ff4f4bfa1cdb0b202ff6.

**Comment by supermaxiste** [comment]
Hi Felix,

thank you for the comprehensive answer and the quick fix. I confirm that 124bp works out. I guess that I was lucky to be unlucky so that now we know about this.

Cheers,
Stefan

**Comment by wbvguo** [comment]
Hi, I also encountered this issue; my case has a length of 100, with -e 0.001, and it got stuck with no data generated.

**Comment by FelixKrueger** [comment]
:( I guess I can only suggest to try to adjust the error rate...
